env:
  H: 8
  W: 8
  mine_count: 10
  guarantee_safe_neighborhood: true
  step_penalty: 0.0001
  progress_scale: 0.6

ppo:
  num_envs: 256
  steps_per_env: 128
  mini_batches: 8
  ppo_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.003
  lr: 0.0003
  max_grad_norm: 0.5
  aux_mine_weight: 0.0
