env:
  H: 16
  W: 16
  mine_count: 40
  guarantee_safe_neighborhood: true
  step_penalty: 0.0001

model:
  name: cnn_residual
  stem_channels: 128
  blocks: 6
  dropout: 0.05
  value_hidden: 256

ppo:
  num_envs: 256
  steps_per_env: 64
  mini_batches: 8
  ppo_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.002
  ent_coef_min: 0.0010
  ent_decay_updates: 400
  lr: 0.0003
  max_grad_norm: 0.5
  aux_mine_weight: 0.0
  aux_mine_calib_weight: 0.0
  total_updates: 1200

training:
  beta_l2: 0.0
  early_stop_patience: 120
  aux_mine_warmup_weight: 0.0
  aux_mine_warmup_updates: 0
  aux_mine_final_weight: 0.0
  aux_mine_decay_power: 1.0
  rollout:
    num_envs: 256
    steps_per_env: 64
