env:
  H: 8
  W: 8
  mine_count: 10
  guarantee_safe_neighborhood: true
  solver_preset: zf_chord
  include_flags_channel: false
  include_frontier_channel: true
  include_progress_channel: true
  include_remaining_mines_channel: true
  progress_scale: 0.6
  step_penalty: 0.0001

model:
  name: cnn_residual
  stem_channels: 128
  blocks: 6
  dropout: 0.05
  value_hidden: 256
  tie_reveal_to_belief: true

ppo:
  num_envs: 64
  steps_per_env: 128
  mini_batches: 8
  ppo_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.002
  ent_coef_min: 0.0015
  ent_decay_updates: 200
  vf_coef: 0.5
  lr: 0.0003
  max_grad_norm: 0.5
  aux_mine_weight: 0.05

training:
  beta_l2: 0.0001
  early_stop_patience: 40
  aux_mine_warmup_weight: 0.05
  aux_mine_warmup_updates: 30
  aux_mine_final_weight: 0.02
  aux_mine_decay_power: 1.0
  rollout:
    num_envs: 64
    steps_per_env: 128
