env:
  H: 12
  W: 12
  mine_count: 20
  guarantee_safe_neighborhood: true
  solver_preset: zf_chord
  include_flags_channel: false
  include_frontier_channel: true
  include_progress_channel: true
  include_remaining_mines_channel: true
  progress_scale: 0.6
  step_penalty: 0.0001

model:
  name: cnn_residual
  stem_channels: 192
  blocks: 10
  dropout: 0.05
  value_hidden: 384
  tie_reveal_to_belief: true

ppo:
  num_envs: 128
  steps_per_env: 128
  mini_batches: 8
  ppo_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.002
  ent_coef_min: 0.0010
  ent_decay_updates: 300
  lr: 0.0003
  max_grad_norm: 0.5
  aux_mine_weight: 0.05
  total_updates: 1500

training:
  beta_l2: 0.0002
  early_stop_patience: 60
  aux_mine_warmup_weight: 0.08
  aux_mine_warmup_updates: 30
  aux_mine_final_weight: 0.05
  aux_mine_decay_power: 1.0
  rollout:
    num_envs: 128
    steps_per_env: 128
