env:
  H: 8
  W: 8
  mine_count: 10
  guarantee_safe_neighborhood: true
  progress_reward: 0.01
  win_reward: 1.0
  loss_reward: -1.0
  step_penalty: 0.0001
  invalid_penalty: 0.001
  use_flag_shaping: false

ppo:
  num_envs: 256
  steps_per_env: 128
  mini_batches: 8
  ppo_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.003
  lr: 0.0003
  max_grad_norm: 0.5
  aux_mine_weight: 0.1
  frontier_mask_until_updates: 200

