env:
  H: 6
  W: 6
  mine_count: 6
  guarantee_safe_neighborhood: true

ppo:
  num_envs: 8
  steps_per_env: 16
  mini_batches: 1
  ppo_epochs: 1
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.0015
  ent_coef_min: 0.001
  ent_decay_updates: 4
  lr: 0.0003
  max_grad_norm: 0.5
  aux_mine_weight: 0.1
  total_updates: 4
