env:
  H: 6
  W: 6
  mine_count: 6
  guarantee_safe_neighborhood: true
  step_penalty: 0.0001
  progress_scale: 0.6

ppo:
  num_envs: 128
  steps_per_env: 128
  mini_batches: 4
  ppo_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.0015
  ent_coef_min: 0.001
  ent_decay_updates: 100
  lr: 0.0003
  max_grad_norm: 0.5
  aux_mine_weight: 0.1
