env:
  H: 6
  W: 6
  mine_count: 6
  guarantee_safe_neighborhood: true
  progress_reward: 0.01
  win_reward: 1.0
  loss_reward: -1.0
  step_penalty: 0.0001
  invalid_penalty: 0.001
  use_flag_shaping: true
  alpha_flag: 0.002
  flag_toggle_cost: 0.002
  chord_enabled: true
  stagnation_cap_factor: 1
  stagnation_penalty: 0.05
  enforce_flag_budget: true
  holding_tax_per_flag: 0.00005

ppo:
  num_envs: 128
  steps_per_env: 128
  mini_batches: 4
  ppo_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.002
  lr: 0.0003
  max_grad_norm: 0.5
  aux_mine_weight: 0.1
  frontier_mask_until_updates: 200
  disable_flags_until_updates: 10

