env:
  H: 16
  W: 16
  guarantee_safe_neighborhood: true
  include_flags_channel: true
  include_frontier_channel: true
  include_progress_channel: true
  include_remaining_mines_channel: true
  mine_count: 40
  progress_scale: 0.6
  step_penalty: 0.0001
model:
  name: transformer
  d_model: 128
  depth: 6
  num_heads: 8
  mlp_ratio: 2.0
  rel_pos_radius: 1
  tie_reveal_to_belief: true
  num_global_tokens: 2
ppo:
  aux_mine_weight: 0.015
  clip_eps: 0.2
  ent_coef: 0.002
  ent_coef_min: 0.0012
  ent_decay_updates: 420
  gae_lambda: 0.95
  gamma: 0.995
  lr: 0.00015
  max_grad_norm: 0.5
  mini_batches: 4
  num_envs: 48
  ppo_epochs: 3
  steps_per_env: 40
  vf_coef: 0.5
training:
  beta_l2: 0.0001
