env:
  H: 16
  W: 16
  mine_count: 40
  guarantee_safe_neighborhood: true
  step_penalty: 0.0001
  progress_scale: 0.6
  include_frontier_channel: true
  include_remaining_mines_channel: true
  include_progress_channel: true
  include_flags_channel: true
model:
  name: transformer
  d_model: 128
  depth: 6
  num_heads: 8
  mlp_ratio: 2.0
  rel_pos_radius: 1
ppo:
  num_envs: 32
  steps_per_env: 48
  mini_batches: 4
  ppo_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.002
  ent_coef_min: 0.0006
  ent_decay_updates: 320
  lr: 0.00015
  max_grad_norm: 0.5
  aux_mine_weight: 0.05
