env:
  H: 8
  W: 8
  mine_count: 10
  guarantee_safe_neighborhood: true
  include_frontier_channel: true
  include_remaining_mines_channel: true
  include_progress_channel: true
  include_flags_channel: true
model:
  name: transformer
  d_model: 128
  depth: 6
  num_heads: 8
  mlp_ratio: 2.0
  rel_pos_radius: 1
ppo:
  num_envs: 192
  steps_per_env: 96
  mini_batches: 8
  ppo_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.0025
  ent_coef_min: 0.0006
  ent_decay_updates: 80
  lr: 0.00025
  max_grad_norm: 0.5
  aux_mine_weight: 0.15
